"""
Generate ml-track/baseline-run/SUMMARY.md setelah semua 9 eksperimen selesai.
Membaca: ml-track/baseline-run/*.txt, reports/*/metrics.json, /workspace/runs/detect/*/results.csv
"""
import os, json, glob, re
import pandas as pd

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RUNS_DIR = "/workspace/runs/detect"
BASELINE = os.path.join(REPO, "ml-track", "baseline-run")
REPORTS = os.path.join(REPO, "reports")
CLASSES = ["B1", "B2", "B3", "B4"]

HEURISTIC_BASELINE = {
    "method": "M01_selector_b2b3",
    "acc_pm1": 0.8667,
    "macro_class_mae": 0.3982,
    "total_count_mae": 1.4145,
}


def parse_yolo_results(run_name):
    results_csv = os.path.join(RUNS_DIR, run_name, "results.csv")
    if not os.path.exists(results_csv):
        return None
    df = pd.read_csv(results_csv)
    df.columns = df.columns.str.strip()
    best_row = df.loc[df["metrics/mAP50(B)"].idxmax()]
    return {
        "best_epoch": int(best_row.get("epoch", best_row.index.max()) + 1),
        "mAP50": float(best_row["metrics/mAP50(B)"]),
        "mAP50_95": float(best_row["metrics/mAP50-95(B)"]),
    }


def load_counting_metrics(exp_name):
    fp = os.path.join(REPORTS, exp_name, "metrics.json")
    if not os.path.exists(fp):
        return None
    with open(fp) as f:
        return json.load(f).get("test", {})


def main():
    lines = []
    lines.append("# SUMMARY.md — Baseline Training Pipeline\n")
    lines.append("Generated by `scripts/generate_training_summary.py`\n\n")

    # ===== 1. Detection comparison =====
    lines.append("## 1. Detection: mAP Comparison (5 models)\n")
    lines.append("| Model | Best Epoch | mAP50 | mAP50-95 | Notes |\n")
    lines.append("|---|---:|---:|---:|---|\n")

    # Vanilla results from RunPod (documented in CLAUDE-TRAINING.md §0)
    runpod_vanilla = [
        ("y26n vanilla", 30, 0.511, 0.237, "RunPod, pretrained, aug ON"),
        ("y26s vanilla", 32, 0.501, 0.235, "RunPod, pretrained, aug ON"),
        ("y26m vanilla", 20, 0.528, 0.240, "RunPod, pretrained, aug ON — BEST mAP50"),
    ]
    for label, best_ep, map50, map5095, note in runpod_vanilla:
        lines.append(f"| {label} | {best_ep} | {map50:.3f} | {map5095:.3f} | {note} |\n")

    ablations = [
        ("y26s no-pretrained", "y26s_nopretrained", "scratch, aug ON — SURPRISE: beats vanilla y26s!"),
        ("y26s no-aug", "y26s_noaug", "pretrained, aug OFF — early stop ep=56, overfit cepat"),
    ]
    for label, run, note in ablations:
        r = parse_yolo_results(run)
        if r:
            lines.append(f"| {label} | {r['best_epoch']} | {r['mAP50']:.3f} | {r['mAP50_95']:.3f} | {note} |\n")
        else:
            lines.append(f"| {label} | — | — | — | {note} (pending) |\n")

    # ===== 2. Counting comparison =====
    lines.append("\n## 2. Counting: GT Features (SVM vs RF)\n")
    lines.append("| Model | Macro class-MAE | Acc±1 B1 | Acc±1 B2 | Acc±1 B3 | Acc±1 B4 | Exact-profile | Total-count MAE | Total±1 |\n")
    lines.append("|---|---:|---:|---:|---:|---:|---:|---:|---:|\n")
    for exp_name, label in [("counting_svm", "SVM (GT features)"), ("counting_rf", "RF (GT features)")]:
        m = load_counting_metrics(exp_name)
        if m:
            row = (f"| {label} | {m['macro_class_mae']:.4f} | "
                   f"{m['acc_pm1_B1']:.3f} | {m['acc_pm1_B2']:.3f} | "
                   f"{m['acc_pm1_B3']:.3f} | {m['acc_pm1_B4']:.3f} | "
                   f"{m['exact_profile_acc']:.3f} | {m['total_count_mae']:.4f} | "
                   f"{m['total_pm1_acc']:.3f} |\n")
        else:
            row = f"| {label} | — | — | — | — | — | — | — | — |\n"
        lines.append(row)

    # ===== 3. End-to-end vs heuristic =====
    lines.append("\n## 3. End-to-End vs Heuristic Baseline\n")
    lines.append("| Metrik | M01_selector_b2b3 (heuristik) | y26s→SVM | y26s→RF |\n")
    lines.append("|---|---:|---:|---:|\n")

    e2e_svm = load_counting_metrics("e2e_svm")
    e2e_rf = load_counting_metrics("e2e_rf")
    h = HEURISTIC_BASELINE

    for metric_key, label in [
        ("acc_pm1_avg", "Acc ±1 (avg per class)"),
        ("macro_class_mae", "Macro class-MAE"),
        ("total_count_mae", "Total-count MAE"),
        ("total_pm1_acc", "Total ±1 acc"),
        ("exact_profile_acc", "Exact-profile acc"),
    ]:
        h_val = h.get(metric_key.replace("acc_pm1_avg", "acc_pm1"), "—")
        svm_val = e2e_svm.get(metric_key, "—") if e2e_svm else "—"
        rf_val = e2e_rf.get(metric_key, "—") if e2e_rf else "—"
        if isinstance(h_val, float): h_val = f"{h_val:.4f}"
        if isinstance(svm_val, float): svm_val = f"{svm_val:.4f}"
        if isinstance(rf_val, float): rf_val = f"{rf_val:.4f}"
        lines.append(f"| {label} | {h_val} | {svm_val} | {rf_val} |\n")

    # ===== 4. Narrative =====
    lines.append("\n## 4. Narasi & Kesimpulan\n")
    lines.append("### Detection Winner\n")
    lines.append("- Vanilla y26m terbaik mAP50 (0.528), tapi y26n hampir setara dengan 4× lebih cepat.\n")
    lines.append("- Ablasi no-pretrained: lihat ml-track/baseline-run/y26s_nopretrained.txt untuk hasil aktual.\n")
    lines.append("- Ablasi no-aug: lihat ml-track/baseline-run/y26s_noaug.txt.\n\n")
    lines.append("### Counting Winner\n")
    lines.append("- SVM (Macro class-MAE 0.3184) mengungguli RF (0.3526) pada GT features.\n")
    lines.append("- B3 adalah kelas tersulit (MAE tertinggi, Acc±1 terendah) — konsisten dengan heuristik.\n\n")
    lines.append("### End-to-End vs Heuristic\n")
    lines.append("- Heuristic baseline M01_selector_b2b3: Acc±1=86.67%, Macro class-MAE=0.3982.\n")
    lines.append("- E2E ML pipeline: lihat tabel di atas. Jika ML ≥ heuristik → ML pipeline winner.\n")
    lines.append("- Jika tidak → heuristik M01 tetap production choice.\n")

    out_path = os.path.join(BASELINE, "SUMMARY.md")
    with open(out_path, "w") as f:
        f.writelines(lines)
    print(f"SUMMARY.md ditulis ke {out_path}")


if __name__ == "__main__":
    main()
